{% set pyproject = load_file_data('pyproject.toml') %}

package:
  name: {{ pyproject.get('project', {}).get('name') }}
  version: {{ pyproject.get('project', {}).get('version') }}

source:
  git_rev: v{{ version }}
  git_url: {{ pyproject.get('project', {}).get('urls', {}).get('"Source"') }}

requirements:
  host:
    - python
    {% for dep in pyproject.get('project', {}).get('dependencies') %}
    - {{ dep }}
    {% endfor %}
  run:
    - python
    {% for dep in pyproject.get('project', {}).get('dependencies') %}
    - {{ dep }}
    {% endfor %}

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

about:
  home: {{ pyproject.get('project', {}).get('urls', {}).get('"Homepage"') }}
  license: {{ pyproject.get('project', {}).get('license') }}
  license_file: {{ pyproject.get('project', {}).get('license', {}).get('file', LICENSE) }}
  summary: {{ pyproject.get('project', {}).get('description') }}
  doc_url: https://aaronkho.gitlab.io/{{ name }}

extra:
  recipe-maintainers:
    - aaronkho
